# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # the root website directory
  publish = "./dist"
  # built command
  command = "echo 'Build in progress...' "
  # the build command
  functions = "functions/"

# App routing

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/oneTouchLambda"
  status = 200

[[redirects]]
  from = "/oneTouch/contactUs"
  to = "/.netlify/functions/nodeMailer"
  status = 200


[[redirects]]
  from = "/oneTouch/customer"
  to = "/.netlify/functions/mongoDB_oneTouchCustomer"
  status = 200



[[redirects]]
  from = "/oneTouch/oneTouchSignUp"
  to = "/.netlify/functions/mongoDB_oneTouchSignUp"
  status = 200

[[redirects]]
  from = "/oneTouch/oneTouchUserAuthentication"
  to = "/.netlify/functions/oneTouchUserAuthentication"
  status = 200
  force = true
