# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # the root website directory
  publish = "./dist"
  # built command
  command = "echo 'Build in progress...' "
  # the build command
  functions = "functions/"

# App routing

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/oneTouchLambda"
  status = 200
