# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # the root website directory
  publish = "./dist"
  # the root website directory
  command = "echo 'I be building' "
  # the build command
  functions = "functions/"

[[redirects]]
  from = "/ndg/tickets"
  to = "/.netlify/functions/freshDeskTickets"
  status = 200

[[redirects]]
  from = "/ndg/createTicket"
  to = "/.netlify/functions/createFreshDeskTicket"
  status = 200

[[redirects]]
  from = "/ndg/contactUs"
  to = "/.netlify/functions/nodeMailer"
  status = 200

[[redirects]]
  from = "/lambdaGET"
  to = "/.netlify/functions/lambdaGET"
  status = 200

[[redirects]]
  from = "/ndg/broadBand"
  to = "/.netlify/functions/icuk"
  status = 200