# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # the root website directory
  publish = "./dist"
  # the root website directory
  command = "echo 'I be building' "
  # the build command
  functions = "functions/"

# App routing

[[redirects]]
  from = "/ndg/tickets"
  to = "/.netlify/functions/freshDeskTickets"
  status = 200

[[redirects]]
  from = "/ndg/createTicket"
  to = "/.netlify/functions/createFreshDeskTicket"
  status = 200

[[redirects]]
  from = "/ndg/contactUs"
  to = "/.netlify/functions/nodeMailer"
  status = 200

[[redirects]]
  from = "/ndg/contactForm"
  to = "/.netlify/functions/nodeMailerIONOS"
  status = 200

[[redirects]]
  from = "/ndg/broadBand"
  to = "/.netlify/functions/icuk"
  status = 200

[[redirects]]
  from = "/ndg/getAddresses/*"
  to = "/.netlify/functions/icukGetAddresses"
  status = 200

[[redirects]]
  from = "/ndg/getAreaBroadbandAvailability/*"
  to = "/.netlify/functions/icukAreaBroadbandAvailability"
  status = 200
  
[[redirects]]
  from = "/ndg/broadbandAvailability"
  to = "/.netlify/functions/broadbandAvailability"
  status = 200

[[redirects]]
  from = "/ndg/users"
  to = "/.netlify/functions/mongoDB_GetUsers"
  status = 200

[[redirects]]
  from = "/ndg/hello"
  to = "/.netlify/functions/redirectLambda"
  status = 301

